-- =====================================================================
-- Garra Delivery — registra no repo o que foi criado via API durante o dev
-- + código fácil (numero) para localizar a tele.
-- =====================================================================

-- Log de webhooks (debug do payload bruto + assinatura)
create table if not exists public.webhook_logs (
  id         uuid primary key default gen_random_uuid(),
  origem     text,
  payload    jsonb,
  headers    jsonb,
  raw        text,
  created_at timestamptz not null default now()
);
alter table public.webhook_logs enable row level security;

-- Cache do auth_token do 99Food por loja
create table if not exists public.food99_tokens (
  app_shop_id   text primary key,
  auth_token    text,
  atualizado_em timestamptz not null default now()
);
alter table public.food99_tokens enable row level security;

-- app_shop_id do 99Food por pedido (p/ enviar status à loja certa)
alter table public.teles add column if not exists food99_app_shop_id text;

-- Código fácil sequencial (ex.: Nº 12) para localizar/comunicar a tele
alter table public.teles add column if not exists numero int generated by default as identity;
